package co.touchlab.droidcon.ui.theme

import androidx.compose.ui.graphics.Color

object Colors {

    val primary = Color(0xFFfa6e50)
    val secondary = Color(0xFF0014e6)
    val secondaryLighter = Color(0xFF4757FF)

    val imageBackground = Color(0xFF999999)
    val darkBlue = Color(0xFF0E65B1)
    val skyBlue = Color(0xFF68D1fD)
    val orange = Color(0xFFF1582C)

    val grey = Color(0xFF868686)
    val darkGrey51 = Color(0xFF333333)
    val darkGrey32 = Color(0xFF202020)
    val lightGrey220 = Color(0xFFDCDCDC)
    val lightGrey222 = Color(0xFFDEDEDE)
    val lightGrey250 = Color(0xFFFAFAFA)

    val droidcon_theme_light_primary = Color(0xFF0014E6)
    val droidcon_theme_light_onPrimary = Color(0xFFFFFFFF)
    val droidcon_theme_light_primaryContainer = Color(0xFFE0E0FF)
    val droidcon_theme_light_onPrimaryContainer = Color(0xFF000569)
    val droidcon_theme_light_secondary = Color(0xFF006B56)
    val droidcon_theme_light_onSecondary = Color(0xFFFFFFFF)
    val droidcon_theme_light_secondaryContainer = Color(0xFF7DE1C3)
    val droidcon_theme_light_onSecondaryContainer = Color(0xFF002018)
    val droidcon_theme_light_tertiary = Color(0xFFF1582C)
    val droidcon_theme_light_onTertiary = Color(0xFFFFFFFF)
    val droidcon_theme_light_tertiaryContainer = Color(0xFFFFDBD1)
    val droidcon_theme_light_onTertiaryContainer = Color(0xFF3B0900)
    val droidcon_theme_light_error = Color(0xFFBA1A1A)
    val droidcon_theme_light_errorContainer = Color(0xFFFFDAD6)
    val droidcon_theme_light_onError = Color(0xFFFFFFFF)
    val droidcon_theme_light_onErrorContainer = Color(0xFF410002)
    val droidcon_theme_light_background = Color(0xFFFAFDFD)
    val droidcon_theme_light_onBackground = Color(0xFF191C1D)
    val droidcon_theme_light_outline = Color(0xFF6F797A)
    val droidcon_theme_light_inverseOnSurface = Color(0xFFEFF1F1)
    val droidcon_theme_light_inverseSurface = Color(0xFF2E3132)
    val droidcon_theme_light_inversePrimary = Color(0xFFBEC2FF)
    val droidcon_theme_light_surfaceTint = Color(0xFF3140FB)
    val droidcon_theme_light_outlineVariant = Color(0xFFBFC8CA)
    val droidcon_theme_light_scrim = Color(0xFF000000)
    val droidcon_theme_light_surface = Color(0xFFF8FAFA)
    val droidcon_theme_light_onSurface = Color(0xFF191C1D)
    val droidcon_theme_light_surfaceVariant = Color(0xFFDBE4E6)
    val droidcon_theme_light_onSurfaceVariant = Color(0xFF3F484A)

    val droidcon_theme_dark_primary = Color(0xFFBEC2FF)
    val droidcon_theme_dark_onPrimary = Color(0xFF000BA6)
    val droidcon_theme_dark_primaryContainer = Color(0xFF0014E6)
    val droidcon_theme_dark_onPrimaryContainer = Color(0xFFE0E0FF)
    val droidcon_theme_dark_secondary = Color(0xFF5FDBB9)
    val droidcon_theme_dark_onSecondary = Color(0xFF00382C)
    val droidcon_theme_dark_secondaryContainer = Color(0xFF005140)
    val droidcon_theme_dark_onSecondaryContainer = Color(0xFF7EF8D5)
    val droidcon_theme_dark_tertiary = Color(0xFFFFB5A0)
    val droidcon_theme_dark_onTertiary = Color(0xFF601400)
    val droidcon_theme_dark_tertiaryContainer = Color(0xFF872000)
    val droidcon_theme_dark_onTertiaryContainer = Color(0xFFFFDBD1)
    val droidcon_theme_dark_error = Color(0xFFFFB4AB)
    val droidcon_theme_dark_errorContainer = Color(0xFF93000A)
    val droidcon_theme_dark_onError = Color(0xFF690005)
    val droidcon_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
    val droidcon_theme_dark_background = Color(0xFF191C1D)
    val droidcon_theme_dark_onBackground = Color(0xFFE1E3E3)
    val droidcon_theme_dark_outline = Color(0xFF899294)
    val droidcon_theme_dark_inverseOnSurface = Color(0xFF191C1D)
    val droidcon_theme_dark_inverseSurface = Color(0xFFE1E3E3)
    val droidcon_theme_dark_inversePrimary = Color(0xFF3140FB)
    val droidcon_theme_dark_surfaceTint = Color(0xFFBEC2FF)
    val droidcon_theme_dark_outlineVariant = Color(0xFF3F484A)
    val droidcon_theme_dark_scrim = Color(0xFF000000)
    val droidcon_theme_dark_surface = Color(0xFF101415)
    val droidcon_theme_dark_onSurface = Color(0xFFC4C7C7)
    val droidcon_theme_dark_surfaceVariant = Color(0xFF3F484A)
    val droidcon_theme_dark_onSurfaceVariant = Color(0xFFBFC8CA)

    val seed = Color(0xFF0014E6)
}
