trigger:
  branches:
    include:
      - 'master'

pr:
  branches:
    include:
      - '*'

pool:
  vmImage: 'macos-10.14'


variables:
  system.debug: true

steps:
      
  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'assembleDebug'
      displayName: 'Building For Android'

  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'test'
      displayName: 'Testing Android'
