use_frameworks!

platform :ios, '9.0'

install! 'cocoapods', :deterministic_uuids => false

target 'iosApp' do
    pod 'Kingfisher', '~> 4.0'
    pod 'MaterialComponents'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
    pod 'lib', :path => '../sessionize/lib'
end
