use_frameworks!

platform :ios, '12.0'

install! 'cocoapods', :deterministic_uuids => false

target 'iosApp' do
    pod 'Kingfisher', '~> 6.3'
    pod 'MaterialComponents'
    pod 'Fabric', '~> 1.10.1'
    pod 'Crashlytics', '~> 3.13.1'
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
    pod 'Firebase/Analytics'
    pod 'Firebase/Firestore'
    pod 'lib', :path => '../sessionize/lib'
end
