use_frameworks!

platform :ios, '14.0'

install! 'cocoapods', :deterministic_uuids => false

target 'Droidcon' do
    pod 'DroidconKit', :path => '../'
    pod 'Kingfisher', '~> 6.3.0'
    pod 'Firebase/Analytics'
end
