use_frameworks!

platform :ios, '14.0'

install! 'cocoapods', :deterministic_uuids => false

target 'Droidcon' do
    pod 'Kingfisher', '~> 7.8.1'
    pod 'Firebase/Analytics'
    pod 'Firebase/Crashlytics'
end
