use_frameworks!

platform :ios, '14.0'

install! 'cocoapods', :deterministic_uuids => false

target 'Droidcon' do
    pod 'Kingfisher', '~> 7.8.1'
    pod 'Sentry', '~> 8.20.0'
    pod 'Firebase/Analytics'
end
